### ISSUE TITLE
Геолокация в Safari 5.1.7 под Windows

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#106]
Не работает контрол геолокации.
Safari 5.1.7 Windows 7

**Comment by egoroof** [comment]
Safari 5.1.7 был последней версией под винду, выпущенный ещё в 2012 году...

**Comment by Trufi** [comment]
Именно поэтому у Safari 5.1 был довольно высокий % аудитории и мы его поддерживали, сейчас он упал
