### ISSUE TITLE
Спрайты при поиске геолокации

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#120]
При геолокации в контроле в момент поиска крутиться спрайт вне зависимости от браузера. 
Скрин 
![selection_001](https://cloud.githubusercontent.com/assets/9331669/5536498/b6ec7198-8ab4-11e4-8dd7-e5ec730e5414.png)
background-image: url(/2.0/img/sprite.dark.png);

При нахождении так же используется спрайт
Скрин
![selection_002](https://cloud.githubusercontent.com/assets/9331669/5536534/5b109768-8ab5-11e4-9c02-6f4ca13607f2.png)
background-image: url(/2.0/img/sprite.basic.png);

**Comment by RLRR** [comment]
Тут ничего не сделаешь. Для этих иконок нет SVG-версий, поэтому они везде отображаются в виде спрайта.
