### ISSUE TITLE
Request timeout on doc website

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#167]
Console out
GET http://counter.yadro.ru/hit;2gis?t25.6;rhttp%3A//api.2gis.ru/doc/maps/manua…ual/popups/;i%u0416%u0436API%20%u043A%u0430%u0440%u0442;0.8091067634522915 net::ERR_TIMED_OUT
UA: Google chrome Version 40.0.2214.111 (64-bit)

**Comment by Trufi** [comment]
Баг не воспроизводится. @andymost в курсе
