### ISSUE TITLE
Отключать возможность зума, если нет тайлов

### ISSUE THREAD

**Issue by ovvost** [2gis/mapsapi#172]
Если зумиться в море, то тайлы пропадают, а возможность зумить остается до 13ого левела.
Хочется, чтобы ограничения по зуму соответствовали наличию тайлов.

**Comment by Trufi** [comment]
В пулл-реквесте https://github.com/2gis/mapsapi/pull/191 возможность зума не пропадает, но после неудачной проверки всех тайлов происходит отзумлевание карты.

**Comment by andymost** [comment]
Already in master
