### ISSUE TITLE
Cyclical world

### ISSUE THREAD

**Issue by ilfa** [2gis/mapsapi#189]
Надо разобраться с поведением цикличного мира.
Некоторые тайлы пропадают на маленьких зумах при перемещении между "мирами".

**Comment by Trufi** [comment]
Проблему с обратной анимацией решил тут https://github.com/2gis/mapsapi/pull/192 .

К сожалению, победить загрузку тайлов не удалось. В новом лифлете баг поправлен, но сильно всё переколбашено и что-то выцепить сложно. Может у кого-то получится лучше, либо отложим до перехода на новую версию лифлета.

Сейчас лучше всего будет просто ограничить пользователя одним миром.

**Comment by ovvost** [comment]
@Trufi ограничение будет у вас?

**Comment by andymost** [comment]
Перешли на новый leaflet. Не воспроизводиться в chrome, firefox, IE8-11. Закрываю
