### ISSUE TITLE
Ошибки в промо

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#227]
При открытии http://2gis.github.io/mapsapi/#themes появляется ошибка:
TypeError: Cannot read property 'match' of undefined  в maps.api.2gis.ru/2.0/js/?version=v2.0.35:10

Также не работает переключение тем.
В консоль сыплется 
Uncaught (in promise) TypeError: Cannot read property 'match' of undefined {stack: (...), message: "Cannot read property 'match' of undefined"}t.exports @ app.js:2t.exports @ app.js:2(anonymous function) @ app.js:2

Проблема в том что в gh-page в js/app.js только минифицированный код.

**Comment by andymost** [comment]
Последний не минифицированный код app.js был тут https://github.com/2gis/mapsapi/commit/0cbcce447537871ecafe0c785c7865c7f4c65282

Минифицированн тут
https://github.com/2gis/mapsapi/commit/7bdbce4aa238343efa7be0233ddcecb08d375732

**Comment by Trufi** [comment]
Поправил http://2gis.github.io/mapsapi
