### ISSUE TITLE
Map with zoom restriction freezes on overzoom

### ISSUE THREAD

**Issue by ilfa** [2gis/mapsapi#236]
Try to zoom by pinch on this demo http://api.2gis.ru/doc/maps/examples/bounds/

**Comment by Trufi** [comment]
It turns out that the bug isn't so simple and pulls a lot of changes from the new leaflet. Maybe postpone up to solve the problems with https://github.com/2gis/mapsapi/pull/198?

**Comment by andymost** [comment]
Fixed.

**Comment by Trufi** [comment]
В новом лифлете бага иногда воспроизводится. Возможно, баг проявляется, когда одно из касаний заезжает на другой дом элемент.

**Comment by Trufi** [comment]
Попробовал воспроизвести, ни в мастере, ни в https://github.com/2gis/mapsapi/pull/304 не воспроизводится
