### ISSUE TITLE
Not to drag the map to nowhere

### ISSUE THREAD

**Issue by ovvost** [2gis/mapsapi#271]
Сейчас можно ограничить карту только баундом, если она не ограничена никак, то на маленьком зуме можно утащить ее с экрана вверх или вниз и видеть область без тайлов и каких-либо упоминаний о карте.
Хотелось бы уметь ограничивать карту не только по баунду, но и по каким-то отдельным измерениям.

**Comment by Trufi** [comment]
@ovvost предлагаю решение-костыль, если у вас включена карта с параметром `worldCopyJump: true`, то можно сделать так:
```javascript
var veryLargeNumber = 2000;
a = DG.latLng(85, veryLargeNumber);
b = DG.latLng(-85, -veryLargeNumber);
c = DG.latLngBounds(a, b);
map.setMaxBounds(c);
```

**Comment by ovvost** [comment]
@Trufi спасибо! Если есть такое вполне нормальное решение, можно закрыть, думаю.

**Comment by Trufi** [comment]
Ок, закрою
