### ISSUE TITLE
Tiles problem in mobile version 2gis.ru

### ISSUE THREAD

**Issue by Trufi** [2gis/mapsapi#275]
С новым mapsapi в мобильной версии в онлайне изначально не подгружаются тайлы.

Если убрать условию в GridLayer:
```
if (!L.Browser.mobileWebkit) {
    this._update(center, tileZoom);
}
```
то всё ок.

**Comment by ovvost** [comment]
Проблема наблюдается при таком сценарии:
```
var map = new DG.Map('map', {
    center: new DG.LatLng(54.980206086231, 82.898068362003),
    zoom: 5
});

map.setZoom(9, {animate: false});
```
то есть при ините карты передаем зум, сразу же после выставляем другой (обязательно с `, {animate: false}`) - всё, на мобилках тайлов нет.

**Comment by Trufi** [comment]
Создал в лифлете issue https://github.com/Leaflet/Leaflet/issues/3659

**Comment by Trufi** [comment]
Поправлено
