### ISSUE TITLE
Map appears blurry after autopanning

### ISSUE THREAD

**Issue by RLRR** [2gis/mapsapi#285]
**Steps to reproduce:**
1. Click on a POI close to the screen edge to activate autopanning

**Result:**
After animation finishes, everything looks slightly washed out and blurry. Gaps between tiles become visible.
![snapshot15](https://cloud.githubusercontent.com/assets/4540062/9408158/74627c36-4829-11e5-87d9-fff075a59198.png)

Might need several attempts to reproduce.

**Comment by andymost** [comment]
Also visible 1px space between tiles

**Comment by RLRR** [comment]
Filed an issue to Leaflet: https://github.com/Leaflet/Leaflet/issues/3913

**Comment by RLRR** [comment]
Fixed here: https://github.com/Leaflet/Leaflet/pull/4046
