### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#291]
Постоянно падающие тесты не отражают картины состояния приложения. Нужно либо добиться их стабилььности, либо выпилить и сделать функциональными.

**Comment by Trufi** [comment]
Сходный тикет https://github.com/2gis/mapsapi/issues/269
Плюс иногда ещё падает тест на `setLang`

**Comment by Trufi** [comment]
Дубликат https://github.com/2gis/mapsapi/pull/269
