### ISSUE TITLE
Check scroll in new FireFox

### ISSUE THREAD

**Issue by Trufi** [2gis/mapsapi#296]
В онлайне с дагбордом в новом firefox выскакивала ошибка из mapsapi связанная со скроллом.

**Comment by ovvost** [comment]
TypeError: t is undefined
Stack trace:
L.Util.extend@http://maps.api.2gis.ru/2.0/js/?pkg=full&version=v2.1.5:6:422
r@http://maps.api.2gis.ru/2.0/loader.js?pkg=full:1:2135
L.Class.extend@http://maps.api.2gis.ru/2.0/js/?pkg=full&version=v2.1.5:6:2807
@http://maps.api.2gis.ru/2.0/js/?pkg=full&version=v2.1.5:10:25101
@http://maps.api.2gis.ru/2.0/js/?pkg=full&version=v2.1.5:6:1

**Comment by Trufi** [comment]
Потыкал в файрфоксе, не воспроизводится, а дагборда уже нет. Нужно будет чинить, когда будет реальный кейс.
