### ISSUE TITLE
[Request] whenTilesReady() method for map object

### ISSUE THREAD

**Issue by myshov** [2gis/mapsapi#309]
It would be great, if there will be possibility to use `whenTilesReady()` method, similar as `map.whenReady()` (http://leafletjs.com/reference.html#map-whenready). I mean possibility to invoke function when tiles was loaded, even this event was already gone.

There is a case in Online4 application when we use print feature. We use iFrame for printing and all tiles loads from browser cache when we try to print several times in order therefore they are loading very fast, so code which should trigger on `tileLoad` event don't invoke, because code which place handler on this event place it after `tileLoad` event.

If there will be `whenTiilesReady()` our code for printing will be more simpler for support.

**Comment by Trufi** [comment]
Hey, you can use `map.baseLayer.isLoading()` and then if this method return true you will subscribe to `tileload` event. If this method return false, you will be sure that tiles are loaded.
