### ISSUE TITLE
Сдвигается страница с картой в IE

### ISSUE THREAD

**Issue by Gaidamak** [2gis/mapsapi#32]
В IEшках открываем нашу карту
Меняем рамер окна браузера по высоте до появления скрола
Устанавливаем страницу так, чтобы контрол зума был виден только на половину
Клацаем в контрол зума

ОР: страница на месте
ФР: страница подвигается вниз

В качестве демо можно использовать http://api.2gis.ru/doc/maps/examples/geocoding/

**Comment by andymost** [comment]
Тикет закрыт по следующим причинам:
1. Смещение страницы до полного отображения контролов скорее фича, нежели баг (воспроизводиться не только в IE)
2. Если имелось отличное поведение влияющие на функциональьность, воспроизвести не удалось.
