### ISSUE TITLE
DGProjectDetector: projectList "id" field

### ISSUE THREAD

**Issue by alekzonder** [2gis/mapsapi#323]
Есть ли какой-то скрытый смысл в том что [здесь](https://github.com/2gis/mapsapi/blob/master/src/DGProjectDetector/src/DGProjectDetector.js#L137) фильтруется параметр id, который есть в ответе от API (region/list) ?

Мне нужно получить id региона, в котором находится пользователь, и потом с ним делать запросы в api для получения рубрик

делаю так 

```js
// до этого получаю projectList из API и присваиваю в DG.projectsList = result.items;

var project = map.projectDetector.getProject();
// там нет id 

// приходится получать весь region/list в цикле перебирать и находить проект
// получение региона из API тоже только по id, по code нельзя

// и потом с id проекта уже иду дальше в API ...
```

если скрытого смысла нет, я добавлю id, пулл-реквест сделаю

**Comment by Trufi** [comment]
Скрытого смысла вроде бы нет
