### ISSUE TITLE
Zoom over maximal with pinch on laptop

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#327]
When zoom over maximal on laptop tiles not visible, look same as first point in #287

**Comment by vkorostelev** [comment]
Also happens by zooming on a maximal level using pinch gesture when one of your fingers stops on controls.

**Comment by Trufi** [comment]
Как костыль, можно инициализировать карту с опцией `bounceAtZoomLimits: false`

```js
var map = DG.map('map', {
    center: [54.980156831455, 82.897440725094],
    zoom: 13,
    bounceAtZoomLimits: false
});
```

В мастере лифлета это бага нет

**Comment by Trufi** [comment]
Поправлено тут https://github.com/2gis/mapsapi/pull/365
