### ISSUE TITLE
Перепутаны местами координаты в api

### ISSUE THREAD

**Issue by slavikse** [2gis/mapsapi#337]
Воспроизводим:
Кликаем [по карте](https://2gis.ru/yaroslavl/search/%D0%A0%D0%B5%D1%81%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%2C%203%D0%BA4/callout/geo-3941285329129055/tab/geo?queryState=center%2F39.88595%2C57.640282%2Fzoom%2F17), забираем uri, парсим и получаем данные:
center/39.88595,57.640282/zoom/17
берем координаты подставляем в api:
center: [39.88595,57.640282]
и видим, что карта совсем в другой точке :(
Если их поменять местами, то точка будет на нужном месте.

ps:
Нет инструмента, чтобы получить координаты по клику на карте?

**Comment by ilfa** [comment]
Формат ссылки на 2gis.ru и интерфейсы API карт не обязательно должны совпадать.

Про формат передачи координат можете прочитать вот [здесь](http://api.2gis.ru/doc/maps/manual/base-classes#класс-dglatlng), а для получения координат по клику вам необходимо подписаться на событие _click_ у карты, описано это вот [здесь](http://api.2gis.ru/doc/maps/manual/map/#события). А вот по [этой](http://api.2gis.ru/doc/maps/examples/events/) ссылке можете ознакомиться с примерами обработки события клика.

**Comment by slavikse** [comment]
Спасибо :)
