### ISSUE TITLE
Wheelscroll changes 2 zoomlevel

### ISSUE THREAD

**Issue by ovvost** [2gis/mapsapi#343]
Windows, Chrome
Build: `gulp build --pkg=DGCustomization,DGPoi,DGEntrance,DGRuler,DGTraffic --no-project-list`

**Comment by alekzonder** [comment]
уже можно закрывать? 

https://github.com/2gis/mapsapi/commit/93d5265fee0b4bf7a9653ffd9584b54041daf013

**Comment by RLRR** [comment]
Да, точно)
