### ISSUE TITLE
Check project detection with screen bound too

### ISSUE THREAD

**Issue by Trufi** [2gis/mapsapi#348]
Сейчас для определения проекта используется положение центра карты, при этом может возникнуть ситуация, когда часть проекта всё же попадает в границу экрана.

Нужно добавить дополнительную проверку для такого случая. А если же в границы экрана будут попадать несколько проектов, то нужно брать ближайший к центру карты.

Т.о. алгоритм выбора проекта будет примерно следующим:
1. Перебирая все проекты, ищем попадание центра карты в границы проекта.
2. Если центр попал в один из проектов, то мы находимся в нем.
3. Если центр не попал ни в один из проектов, то мы проверяем пересечения границ экрана с границами проектов.
4. Если набралось несколько таких проектов, то ищем ближайшую границу к центру карты.

**Comment by vkorostelev** [comment]
Решено в #383.
