### ISSUE TITLE
Migrate from HTTP to HTTPS

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [2gis/mapsapi#381]
IMO, it's time to migrate _all_ 2GIS projects _on all domains and subdomains_ from HTTP to HTTPS.

There are 2 main problems:

1) many powerful features (e.g. geolocation) no longer work on insecure origins in the latest versions of all mainstream browsers (e.g. in Chromium-based browsers — https://goo.gl/rStTGz);

2) many 2GIS projects on various domains and subdomains have no valid HTTPS certificates and have mixed content (the page loads over HTTPS, but requests an insecure scripts/stylesheets/images, etc.).

Let's start from fixing all HTTPS-related issues on api.2gis.ru.

E.g. when the user opens http://api.2gis.ru/doc/maps/ru/examples/base/ URL, "Location access denied." alert box displays and the last example on the page doesn't work.

I can change `<script src="http://maps.api.2gis.ru/2.0/loader.js"></script>` to `<script src="https://maps.api.2gis.ru/2.0/loader.js"></script>` in all examples and submit pull request, if you want. ;)

Could you please fix all problems with HTTPS certificate and enable HSTS when all mixed content issues will be fixed?

**Comment by Trufi** [comment]
We are working on it, but the issue requires solving some problems of internal infrastructure.

**Comment by Trufi** [comment]
Now https://api.2gis.ru/doc/maps/ru/examples/base/ works fine
