### ISSUE TITLE
Непонятное поведение попапа с настройкой zoomAnimation: false

### ISSUE THREAD

**Issue by login2030** [2gis/mapsapi#390]
Проблема в том, что если открыть попап и изменить масштаб, то стандартный попап начинает появляться вразных местах карты, либо не появляется вовсе. Варианта два, либо я не понял, как это работает, либо это баг. Вот демо - http://codepen.io/login2030/pen/NbaYzZ

**Comment by alik0211** [comment]
У меня не получается воспроизвести ошибку. Наверно, её исправили, а про ишью забыли.

Если проблемы больше нет, кто-нибудь закройте это ишью.
