### ISSUE TITLE
TypeError: Cannot read property 'lat' of null

### ISSUE THREAD

**Issue by AntonRatnick** [2gis/mapsapi#397]
Hi,
on mouse over the map I have an error: "TypeError: Cannot read property 'lat' of null";

It looks like map try to get info about objects under cursos but the respons is not valid

this.map = DG.map('map', {
            center: this.props.mapCenterPoint.getCoordinatesArray(),
            zoom: zoom,
            fullscreenControl: false,
            zoomControl: false
        });

my activation code

**Comment by egoroof** [comment]
What does `this.props.mapCenterPoint.getCoordinatesArray()` return?

**Comment by AntonRatnick** [comment]
this method returns [55.74, 37.62]

params which I use in DG.map function doesn't matter to result

**Comment by egoroof** [comment]
Have you seen https://github.com/2gis/2gis-maps-react?

**Comment by AntonRatnick** [comment]
Yes, but I need typings for typescript and I decided to create my own cover
