### ISSUE TITLE
dustjs-linkedin vulnerabilities

### ISSUE THREAD

**Issue by egoroof** [2gis/mapsapi#422]
https://nodesecurity.io/check/2gis-maps 3 уязвимости в  `dustjs-linkedin@2.7.2`
В поиске https://npms.io/search?q=2gis-maps показывает плашку `insecure`
Нужно обновить.

**Comment by Trufi** [comment]
Хорошее замечание.
Кажется, все уязвимости связаны с не нашим случаем, а именно серверным использованием пакета, но все равно надо обновить.
