### ISSUE TITLE
sudo gulp test --ff

### ISSUE THREAD

**Issue by operasfantom** [2gis/mapsapi#449]
CHUNK #0
............................................
Firefox 26.0.0 (Ubuntu 0.0.0) DGMap #panBy should set zoom to 13 after panBy to place without project FAILED
	expected 15 to equal 13
	Assertion.prototype.assert@/home/bi/Documents/mapsapi-master/node_modules/expect.js/index.js:96
	Assertion.prototype.equal@/home/bi/Documents/mapsapi-master/node_modules/expect.js/index.js:219
	@/home/bi/Documents/mapsapi-master/node_modules/expect.js/index.js:69
	@/home/bi/Documents/mapsapi-master/src/DGCustomization/test/DGMapSpec.js:89
	
...............
Firefox 26.0.0 (Ubuntu 0.0.0) GridLayer number of 256px tiles loaded in synchronous animated grid @800x600px Loads 32, unloads 16 tiles zooming in 10-11 FAILED
	Error: expected 12 to equal 16 (/home/bi/Documents/mapsapi-master/node_modules/expect.js/index.js:96)

**Comment by Trufi** [comment]
We support unit tests only in Phantom. In other browsers tests can be broken.
