### ISSUE TITLE
Why does the test require 13 instead of 15? PATH: src\DGCustomization\test

### ISSUE THREAD

**Issue by operasfantom** [2gis/mapsapi#450]
describe('#panBy', function () {
        it('should set zoom to 13 after panBy to place without project', function () {
            map.setView([55.005582426668404, 82.93081283569337], 15, {animate: false}); //15?
            map.panBy([1e15, 0]);
            expect(map.getZoom()).to.be(13); //13?
        });
    });

**Comment by Trufi** [comment]
Because `map.baseLayer` contains tiles up to 13 zoom by default, and up to 18 zoom in 2GIS regions. If a user move outside of the region, map will zoom out automatically. The mechanic will disable, if another tile layer add to the map.
