### ISSUE TITLE
Geocoder api?

### ISSUE THREAD

**Issue by b1rdex** [2gis/mapsapi#479]
There was `DG.Geocoder.get` in v1 to get geo point of provided address.
Is there any replacement provided? How can I get coordinates for given address?

**Comment by scherebedov** [comment]
Hi. New mapsapi haven't special geocoder function. Now it is non free function of api.  You can use http://partner.api.2gis.ru/

**Comment by GlennMiller1991** [comment]
but now there is geoclicker property of map instance. Can i intercept returned address by geoclick handler?
