### ISSUE TITLE
Заголовки балунов на OS X при медленном коннекте

### ISSUE THREAD

**Issue by andymost** [2gis/mapsapi#89]
При медленном коннекте если не успевают прогрузится шрифты  при открытии балуна используется системный из-за чего возникают такие случаи на OS X
![4ff52d271b](https://cloud.githubusercontent.com/assets/9331669/5181895/b6033694-74bc-11e4-9799-9cce941689fb.jpg)
На Windows 7 Chrome и Ubuntu 14.04 Chrome  не проявляется

**Comment by RLRR** [comment]
Шрифтов у нас давно нет, так что тикет закрываю)
